# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mini-project-search-filter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourProjectName
    pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON'
pod ‘SwiftRangeSlider’
end
